### PR TITLE
changed one histogram to ggformula

### PR DESCRIPTION
**Pull request by mchien20**

### CODE REVIEW

**Review by nicholasjhorton — CHANGES_REQUESTED** [review]
Margaret, you added a *lot* of temporary files that aren't wanted in the repo into the repo.  Can you please only commit changes to files that were already in the repo?  Otherwise, we're likely to run into merge conflict problems in the future.

**Comment by nicholasjhorton** [comment]
You may need to abandon this fork and project rather than removing the files from github control.  (@rpruim may have a better suggestion, but my idea won't take more than a few minutes.)

**Comment by mchien20** [comment]
I'm not sure how I added temporary files.. What should I do next time to avoid that?

**Comment by nicholasjhorton** [comment]
Can we talk briefly after class tomorrow?

Nick


> On Feb 22, 2018, at 8:54 PM, mchien20 <notifications@github.com> wrote:
> 
> I'm not sure how I added temporary files.. What should I do next time to avoid that?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Pull request closed without merging**
