### PR TITLE
added spaces, fixed the dotplot

### PR DESCRIPTION
**Pull request by mchien20**
Still unsure about normal plots and overlay

### CODE REVIEW

**Review by nicholasjhorton — APPROVED** [review]
We may want to rethink the use of filter inside of gf_dotplot() (but I've approved this change).

**Comment by nicholasjhorton** [comment]
Can you include a minimally reproducible example of what you are referring to?  

I suspect that it's the lines: 
densityplot(~ cesd, data=female)
ladd(grid.text(x=0.2, y=0.8, 'only females'))
ladd(panel.mathdensity(args=list(mean=mean(cesd),
  sd=sd(cesd)), col="red"), data=female)
ladd(panel.abline(v=60, lty=2, lwd=2, col="grey"))

but I'm not 100% sure.

**Comment by mchien20** [comment]
Those are the lines I'm referring to (lines 200-205)

**Comment by rpruim** [comment]
While these edits are going on, should we also captialize `Female`?  (I like capitalization for data frames.)

**Comment by rpruim** [comment]
If you are not able to figure out the code chunk above, create a reproducible example (preferably using `reprex::reprex()`, and I'll lend a hand.

**Comment by mchien20** [comment]
I'm not sure how to use reprex and how it relates to this plot.

**Comment by nicholasjhorton** [comment]
We've figured this out (using gf_refine()): apologies for the extra emails.

**Comment by rpruim** [comment]
reprex is a package and its reprex() function creates reproducible examples that can be pasted into github issues.  The resulting post will show code, output, and plots, but reprex() will fail if the example is not completely reproducible.

Here is an example in another issue: https://github.com/ProjectMOSAIC/ggformula/issues/89

**Pull request merged**
